name: .NET Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ./csharp/LeetCodeProblems.sln

      - name: Build
        run: dotnet build ./csharp/LeetCodeProblems.sln --no-restore --configuration Release

      - name: Run tests
        run: dotnet test ./csharp/LeetCodeProblems.Tests/LeetCodeProblems.Tests.csproj --no-build --verbosity normal
